// Generated by scripts/generate-audit-validators.mjs from contracts/openapi.json.
// Do not edit this file directly.

import { z } from "zod";

export const PlatformAuditTrailEvent = z.discriminatedUnion("eventType", [
  z
    .object({
      eventType: z.literal("audit.trail.platform_read"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      scope: z.literal("PLATFORM"),
      companyPublicId: z.null(),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
          })
          .strict(),
        z
          .object({
            kind: z.literal("PLATFORM_ADMIN"),
            publicId: z.string().uuid(),
          })
          .strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      origin: z
        .object({
          ip: z.union([z.string(), z.null()]),
          userAgent: z.union([z.string(), z.null()]),
        })
        .strict(),
      targets: z.array(z.object({ targetType: z.string(), publicId: z.string() }).strict()),
      details: z
        .object({
          companyPublicId: z.union([z.string(), z.null()]),
          scope: z.union([z.literal("PLATFORM"), z.literal("COMPANY"), z.null()]),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.profile.material_updated"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      scope: z.literal("COMPANY"),
      companyPublicId: z.string().uuid(),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
          })
          .strict(),
        z
          .object({
            kind: z.literal("PLATFORM_ADMIN"),
            publicId: z.string().uuid(),
          })
          .strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      origin: z
        .object({
          ip: z.union([z.string(), z.null()]),
          userAgent: z.union([z.string(), z.null()]),
        })
        .strict(),
      targets: z.array(z.object({ targetType: z.string(), publicId: z.string() }).strict()),
      details: z
        .object({
          changes: z.array(
            z
              .object({
                field: z.union([
                  z.literal("name"),
                  z.literal("country"),
                  z.literal("taxNumber"),
                  z.literal("commercialNumber"),
                ]),
                before: z.union([z.string(), z.null()]),
                after: z.union([z.string(), z.null()]),
              })
              .strict(),
          ),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.profile.completed"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      scope: z.literal("COMPANY"),
      companyPublicId: z.string().uuid(),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
          })
          .strict(),
        z
          .object({
            kind: z.literal("PLATFORM_ADMIN"),
            publicId: z.string().uuid(),
          })
          .strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      origin: z
        .object({
          ip: z.union([z.string(), z.null()]),
          userAgent: z.union([z.string(), z.null()]),
        })
        .strict(),
      targets: z.array(z.object({ targetType: z.string(), publicId: z.string() }).strict()),
      details: z
        .object({
          beforeStatus: z.union([z.literal("INCOMPLETE"), z.literal("COMPLETE")]),
          afterStatus: z.literal("COMPLETE"),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("audit.event.unavailable"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      reason: z.literal("UNSUPPORTED_OR_DAMAGED"),
    })
    .strict(),
]);

export const platformAuditTrailPageEnvelopeSchema = z
  .object({
    items: z.array(z.unknown()),
    nextCursor: z.union([z.string(), z.null()]),
    hasMore: z.boolean(),
  })
  .strict();

export type PlatformAuditTrailEvent = z.infer<typeof PlatformAuditTrailEvent>;

export interface UnrecognizedPlatformAuditTrailEvent {
  eventType: "__unrecognized__";
  raw: unknown;
}

export type PlatformAuditTrailItem = PlatformAuditTrailEvent | UnrecognizedPlatformAuditTrailEvent;

export interface PlatformAuditTrailPage
  extends Omit<z.infer<typeof platformAuditTrailPageEnvelopeSchema>, "items"> {
  items: PlatformAuditTrailItem[];
}

export function parsePlatformAuditTrailPage(value: unknown): PlatformAuditTrailPage {
  const envelope = platformAuditTrailPageEnvelopeSchema.parse(value);

  return {
    ...envelope,
    items: envelope.items.map(parsePlatformAuditTrailItem),
  };
}

function parsePlatformAuditTrailItem(raw: unknown): PlatformAuditTrailItem {
  const result = PlatformAuditTrailEvent.safeParse(raw);
  if (result.success) return result.data;

  return { eventType: "__unrecognized__", raw };
}
