import type { LeadWithContacts } from "./api";

export const dummyLeads: LeadWithContacts[] = [
  {
    lead: {
      publicId: "lead-001",
      companyName: "TechCorp Arabia",
      website: "https://techcorp.sa",
      industry: "Technology",
      companySizeRange: "21_TO_50",
      country: "SA",
      city: "Riyadh",
      source: "LINKEDIN",
      status: "QUALIFIED",
      lostReason: null,
      ownerUserId: null,
      numberOfAttempts: 4,
      companyId: null,
      createdAt: "2026-05-10T10:00:00.000Z",
      updatedAt: "2026-05-16T09:00:00.000Z",
      deletedAt: null,
    },
    contacts: [
      {
        publicId: "cnt-001",
        name: "Mohammed Al-Faisal",
        email: "m.faisal@techcorp.sa",
        phone: "+966501234567",
        jobTitle: "CEO",
        isPrimary: true,
      },
    ],
  },
  {
    lead: {
      publicId: "lead-002",
      companyName: "Horizon Fintech",
      website: "https://horizonfin.ae",
      industry: "Fintech",
      companySizeRange: "51_TO_100",
      country: "AE",
      city: "Dubai",
      source: "REFERRAL",
      status: "DEMO_SCHEDULED",
      lostReason: null,
      ownerUserId: null,
      numberOfAttempts: 2,
      companyId: null,
      createdAt: "2026-05-12T10:00:00.000Z",
      updatedAt: "2026-05-17T10:00:00.000Z",
      deletedAt: null,
    },
    contacts: [
      {
        publicId: "cnt-002",
        name: "Sara Al-Rashid",
        email: "s.rashid@horizonfin.ae",
        phone: "+971507654321",
        jobTitle: "COO",
        isPrimary: true,
      },
    ],
  },
  {
    lead: {
      publicId: "lead-003",
      companyName: "Medika Health",
      website: null,
      industry: "Healthcare",
      companySizeRange: "MORE_THAN_100",
      country: "SA",
      city: "Jeddah",
      source: "GOOGLE",
      status: "CONTACTED",
      lostReason: null,
      ownerUserId: null,
      numberOfAttempts: 1,
      companyId: null,
      createdAt: "2026-05-14T10:00:00.000Z",
      updatedAt: "2026-05-14T10:00:00.000Z",
      deletedAt: null,
    },
    contacts: [
      {
        publicId: "cnt-003",
        name: "Khaled Al-Ghamdi",
        email: "k.ghamdi@medika.sa",
        phone: "+966551234567",
        jobTitle: "HR Director",
        isPrimary: true,
      },
    ],
  },
  {
    lead: {
      publicId: "lead-004",
      companyName: "RetailPro Group",
      website: "https://retailpro.sa",
      industry: "Retail",
      companySizeRange: "MORE_THAN_100",
      country: "SA",
      city: "Riyadh",
      source: "LANDING_PAGE",
      status: "NEGOTIATION",
      lostReason: null,
      ownerUserId: null,
      numberOfAttempts: 6,
      companyId: null,
      createdAt: "2026-04-28T10:00:00.000Z",
      updatedAt: "2026-05-18T10:00:00.000Z",
      deletedAt: null,
    },
    contacts: [
      {
        publicId: "cnt-004",
        name: "Nora Al-Otaibi",
        email: "n.otaibi@retailpro.sa",
        phone: "+966509871234",
        jobTitle: "CEO",
        isPrimary: true,
      },
    ],
  },
  {
    lead: {
      publicId: "lead-005",
      companyName: "EduSphere Academy",
      website: "https://edusphere.sa",
      industry: "Education",
      companySizeRange: "5_TO_20",
      country: "SA",
      city: "Dammam",
      source: "PARTNER",
      status: "NEW",
      lostReason: null,
      ownerUserId: null,
      numberOfAttempts: 0,
      companyId: null,
      createdAt: "2026-05-20T10:00:00.000Z",
      updatedAt: "2026-05-20T10:00:00.000Z",
      deletedAt: null,
    },
    contacts: [],
  },
  {
    lead: {
      publicId: "lead-006",
      companyName: "LogiChain Solutions",
      website: "https://logichain.com",
      industry: "Logistics",
      companySizeRange: "51_TO_100",
      country: "SA",
      city: "Riyadh",
      source: "LINKEDIN",
      status: "LOST",
      lostReason: "TOO_EXPENSIVE",
      ownerUserId: null,
      numberOfAttempts: 5,
      companyId: null,
      createdAt: "2026-04-15T10:00:00.000Z",
      updatedAt: "2026-05-05T10:00:00.000Z",
      deletedAt: null,
    },
    contacts: [
      {
        publicId: "cnt-006",
        name: "Ahmad Al-Zahrani",
        email: "a.zahrani@logichain.sa",
        phone: "+966502345678",
        jobTitle: "Operations Manager",
        isPrimary: true,
      },
    ],
  },
];
