// Generated by scripts/generate-audit-validators.mjs from contracts/openapi.json.
// Do not edit this file directly.

import { z } from "zod";

// Company projections intentionally omit Platform Admin identifiers so company readers only learn that Edara acted.
export const CompanyAuditTrailEvent = z.discriminatedUnion("eventType", [
  z
    .object({
      eventType: z.literal("company.profile.material_updated"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          changes: z.array(
            z
              .object({
                field: z.union([
                  z.literal("name"),
                  z.literal("country"),
                  z.literal("taxNumber"),
                  z.literal("commercialNumber"),
                ]),
                before: z.union([z.string(), z.null()]),
                after: z.union([z.string(), z.null()]),
              })
              .strict(),
          ),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.profile.completed"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          beforeStatus: z.union([z.literal("INCOMPLETE"), z.literal("COMPLETE")]),
          afterStatus: z.literal("COMPLETE"),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.lifecycle.created"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          name: z.string(),
          companyCode: z.string(),
          lifecycleStatus: z.string(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.lifecycle.updated"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          changes: z.array(
            z
              .object({
                field: z.union([
                  z.literal("name"),
                  z.literal("country"),
                  z.literal("website"),
                  z.literal("addressLine"),
                  z.literal("isActive"),
                ]),
                before: z.union([z.string(), z.null()]),
                after: z.union([z.string(), z.null()]),
              })
              .strict(),
          ),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.lifecycle.deleted"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ reason: z.union([z.string(), z.null()]) }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.lifecycle.restored"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ reason: z.union([z.string(), z.null()]) }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.lifecycle.frozen"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ reason: z.union([z.string(), z.null()]) }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.lifecycle.unfrozen"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ reason: z.union([z.string(), z.null()]) }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.lifecycle.suspended"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ reason: z.union([z.string(), z.null()]) }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.lifecycle.unsuspended"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ reason: z.union([z.string(), z.null()]) }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.access-policy.changed"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          previousMode: z.union([
            z.literal("NORMAL"),
            z.literal("READ_ONLY"),
            z.literal("FROZEN"),
            z.literal("BLOCKED"),
            z.literal("MAINTENANCE"),
          ]),
          mode: z.union([
            z.literal("NORMAL"),
            z.literal("READ_ONLY"),
            z.literal("FROZEN"),
            z.literal("BLOCKED"),
            z.literal("MAINTENANCE"),
          ]),
          reason: z.string(),
          note: z.union([z.string(), z.null()]),
          effectiveFrom: z.string(),
          effectiveUntil: z.union([z.string(), z.null()]),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.access-policy.denied"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          effectiveMode: z.union([
            z.literal("NORMAL"),
            z.literal("READ_ONLY"),
            z.literal("FROZEN"),
            z.literal("BLOCKED"),
            z.literal("MAINTENANCE"),
          ]),
          operation: z.union([z.literal("read"), z.literal("write"), z.literal("onboarding")]),
          lifecycleStatus: z.string(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.setup.step_started"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          stepType: z.union([
            z.literal("SET_COMPANY_PROFILE"),
            z.literal("SET_ROLES"),
            z.literal("SET_JOBS"),
            z.literal("SET_BRANCHES"),
            z.literal("SET_SHIFTS"),
            z.literal("SET_DEPARTMENTS"),
          ]),
          status: z.union([
            z.literal("PENDING"),
            z.literal("IN_PROGRESS"),
            z.literal("COMPLETED"),
            z.literal("SKIPPED"),
          ]),
          isRequired: z.boolean(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.setup.step_completed"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          stepType: z.union([
            z.literal("SET_COMPANY_PROFILE"),
            z.literal("SET_ROLES"),
            z.literal("SET_JOBS"),
            z.literal("SET_BRANCHES"),
            z.literal("SET_SHIFTS"),
            z.literal("SET_DEPARTMENTS"),
          ]),
          status: z.union([
            z.literal("PENDING"),
            z.literal("IN_PROGRESS"),
            z.literal("COMPLETED"),
            z.literal("SKIPPED"),
          ]),
          isRequired: z.boolean(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.setup.step_skipped"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          stepType: z.union([
            z.literal("SET_COMPANY_PROFILE"),
            z.literal("SET_ROLES"),
            z.literal("SET_JOBS"),
            z.literal("SET_BRANCHES"),
            z.literal("SET_SHIFTS"),
            z.literal("SET_DEPARTMENTS"),
          ]),
          status: z.union([
            z.literal("PENDING"),
            z.literal("IN_PROGRESS"),
            z.literal("COMPLETED"),
            z.literal("SKIPPED"),
          ]),
          isRequired: z.boolean(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.activation.activated"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          activatedAt: z.union([z.string(), z.null()]),
          lifecycleStatus: z.string(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.subscription.trial_extended"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          previousTrialEndDate: z.string(),
          trialEndDate: z.string(),
          reason: z.string(),
          planPublicId: z.string(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.subscription.trial_expired"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          trialEndDate: z.string(),
          expiredAt: z.string(),
          accessMode: z.string(),
          planPublicId: z.string(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("user.lifecycle.created"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          employeeCode: z.union([z.string(), z.null()]),
          status: z.string(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("user.lifecycle.updated"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          employeeCode: z.union([z.string(), z.null()]),
          changedFields: z.array(z.string()),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("user.lifecycle.deleted"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ employeeCode: z.union([z.string(), z.null()]) }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("email.template_assignment.assigned"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          emailTypeKey: z.string(),
          templateRevisionKey: z.string(),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("email.template_assignment.removed"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ emailTypeKey: z.string() }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("email.template_assignment.migrated"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          emailTypeKey: z.string(),
          fromRevisionKey: z.string(),
          toRevisionKey: z.string(),
          reason: z.union([z.string(), z.null()]),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("auth.session.started"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          clientType: z.string(),
          usedTemporaryCredentials: z.boolean(),
          reason: z.union([z.string(), z.null()]),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("auth.session.ended"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ reason: z.string() }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("auth.session.revoked"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ reason: z.string() }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("auth.session.refreshed"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ familyId: z.string() }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("auth.credential.password_changed"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ usedTemporaryCredentials: z.boolean() }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("auth.credential.reset_forced"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({}).partial().strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("auth.invitation.issued"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z.object({ reissued: z.boolean() }).strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("auth.invitation.accepted"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
            name: z.union([z.string(), z.null()]),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
        z.object({ kind: z.literal("ERASED_USER") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(
        z
          .object({
            targetType: z.string(),
            publicId: z.string(),
            name: z.union([z.string(), z.null()]).optional(),
          })
          .strict(),
      ),
      details: z
        .object({
          clientType: z.string(),
          reason: z.union([z.string(), z.null()]),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("audit.event.unavailable"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      reason: z.literal("UNSUPPORTED_OR_DAMAGED"),
    })
    .strict(),
]);

export const companyAuditTrailPageEnvelopeSchema = z
  .object({
    items: z.array(z.unknown()),
    nextCursor: z.union([z.string(), z.null()]),
    hasMore: z.boolean(),
  })
  .strict();

export type CompanyAuditTrailEvent = z.infer<typeof CompanyAuditTrailEvent>;

export interface UnrecognizedCompanyAuditTrailEvent {
  eventType: "__unrecognized__";
  raw: unknown;
}

export type CompanyAuditTrailItem = CompanyAuditTrailEvent | UnrecognizedCompanyAuditTrailEvent;

export interface CompanyAuditTrailPage
  extends Omit<z.infer<typeof companyAuditTrailPageEnvelopeSchema>, "items"> {
  items: CompanyAuditTrailItem[];
}

export function parseCompanyAuditTrailPage(value: unknown): CompanyAuditTrailPage {
  const envelope = companyAuditTrailPageEnvelopeSchema.parse(value);

  return {
    ...envelope,
    items: envelope.items.map(parseCompanyAuditTrailItem),
  };
}

function parseCompanyAuditTrailItem(raw: unknown): CompanyAuditTrailItem {
  const result = CompanyAuditTrailEvent.safeParse(raw);
  if (result.success) return result.data;

  return { eventType: "__unrecognized__", raw };
}
