// Generated by scripts/generate-audit-validators.mjs from contracts/openapi.json.
// Do not edit this file directly.

import { z } from "zod";

// Company projections intentionally omit Platform Admin identifiers so company readers only learn that Edara acted.
export const CompanyAuditTrailEvent = z.discriminatedUnion("eventType", [
  z
    .object({
      eventType: z.literal("company.profile.material_updated"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(z.object({ targetType: z.string(), publicId: z.string() }).strict()),
      details: z
        .object({
          changes: z.array(
            z
              .object({
                field: z.union([
                  z.literal("name"),
                  z.literal("country"),
                  z.literal("taxNumber"),
                  z.literal("commercialNumber"),
                ]),
                before: z.union([z.string(), z.null()]),
                after: z.union([z.string(), z.null()]),
              })
              .strict(),
          ),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("company.profile.completed"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      outcome: z.union([z.literal("SUCCESS"), z.literal("FAILURE")]),
      actor: z.union([
        z
          .object({
            kind: z.literal("USER"),
            publicId: z.string().uuid(),
          })
          .strict(),
        z.object({ kind: z.literal("PLATFORM_ADMIN") }).strict(),
        z
          .object({
            kind: z.literal("SYSTEM"),
            component: z.union([
              z.literal("EMAIL_WORKER"),
              z.literal("SCHEDULER"),
              z.literal("SCRIPT"),
            ]),
          })
          .strict(),
        z.object({ kind: z.literal("ANONYMOUS") }).strict(),
        z.object({ kind: z.literal("ATTRIBUTION_FAILED") }).strict(),
      ]),
      traceId: z.union([z.string(), z.null()]),
      targets: z.array(z.object({ targetType: z.string(), publicId: z.string() }).strict()),
      details: z
        .object({
          beforeStatus: z.union([z.literal("INCOMPLETE"), z.literal("COMPLETE")]),
          afterStatus: z.literal("COMPLETE"),
        })
        .strict(),
    })
    .strict(),
  z
    .object({
      eventType: z.literal("audit.event.unavailable"),
      eventVersion: z.literal(1),
      occurredAt: z.string().datetime({ offset: true }),
      reason: z.literal("UNSUPPORTED_OR_DAMAGED"),
    })
    .strict(),
]);

export const companyAuditTrailPageEnvelopeSchema = z
  .object({
    items: z.array(z.unknown()),
    nextCursor: z.union([z.string(), z.null()]),
    hasMore: z.boolean(),
  })
  .strict();

export type CompanyAuditTrailEvent = z.infer<typeof CompanyAuditTrailEvent>;

export interface UnrecognizedCompanyAuditTrailEvent {
  eventType: "__unrecognized__";
  raw: unknown;
}

export type CompanyAuditTrailItem = CompanyAuditTrailEvent | UnrecognizedCompanyAuditTrailEvent;

export interface CompanyAuditTrailPage
  extends Omit<z.infer<typeof companyAuditTrailPageEnvelopeSchema>, "items"> {
  items: CompanyAuditTrailItem[];
}

export function parseCompanyAuditTrailPage(value: unknown): CompanyAuditTrailPage {
  const envelope = companyAuditTrailPageEnvelopeSchema.parse(value);

  return {
    ...envelope,
    items: envelope.items.map(parseCompanyAuditTrailItem),
  };
}

function parseCompanyAuditTrailItem(raw: unknown): CompanyAuditTrailItem {
  const result = CompanyAuditTrailEvent.safeParse(raw);
  if (result.success) return result.data;

  return { eventType: "__unrecognized__", raw };
}
