import type { SearchableSelectOption } from "@/shared/ui/searchable-select";

export const PLAN_CURRENCY_OPTIONS: SearchableSelectOption[] = [
  { value: "USD", label: "USD - US dollar" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "GBP", label: "GBP - British pound" },
  { value: "EGP", label: "EGP - Egyptian pound" },
  { value: "SAR", label: "SAR - Saudi riyal" },
  { value: "AED", label: "AED - UAE dirham" },
  { value: "QAR", label: "QAR - Qatari riyal" },
  { value: "KWD", label: "KWD - Kuwaiti dinar" },
  { value: "BHD", label: "BHD - Bahraini dinar" },
  { value: "OMR", label: "OMR - Omani rial" },
  { value: "JOD", label: "JOD - Jordanian dinar" },
  { value: "MAD", label: "MAD - Moroccan dirham" },
  { value: "DZD", label: "DZD - Algerian dinar" },
  { value: "TND", label: "TND - Tunisian dinar" },
  { value: "TRY", label: "TRY - Turkish lira" },
  { value: "INR", label: "INR - Indian rupee" },
  { value: "PKR", label: "PKR - Pakistani rupee" },
  { value: "CNY", label: "CNY - Chinese yuan" },
  { value: "JPY", label: "JPY - Japanese yen" },
  { value: "CAD", label: "CAD - Canadian dollar" },
  { value: "AUD", label: "AUD - Australian dollar" },
  { value: "CHF", label: "CHF - Swiss franc" },
  { value: "SEK", label: "SEK - Swedish krona" },
  { value: "NOK", label: "NOK - Norwegian krone" },
  { value: "DKK", label: "DKK - Danish krone" },
];

export const PLAN_COUNTRY_OPTIONS: SearchableSelectOption[] = [
  { value: "EG", label: "EG - Egypt" },
  { value: "SA", label: "SA - Saudi Arabia" },
  { value: "AE", label: "AE - United Arab Emirates" },
  { value: "QA", label: "QA - Qatar" },
  { value: "KW", label: "KW - Kuwait" },
  { value: "BH", label: "BH - Bahrain" },
  { value: "OM", label: "OM - Oman" },
  { value: "JO", label: "JO - Jordan" },
  { value: "LB", label: "LB - Lebanon" },
  { value: "MA", label: "MA - Morocco" },
  { value: "DZ", label: "DZ - Algeria" },
  { value: "TN", label: "TN - Tunisia" },
  { value: "TR", label: "TR - Turkey" },
  { value: "US", label: "US - United States" },
  { value: "GB", label: "GB - United Kingdom" },
  { value: "DE", label: "DE - Germany" },
  { value: "FR", label: "FR - France" },
  { value: "IT", label: "IT - Italy" },
  { value: "ES", label: "ES - Spain" },
  { value: "NL", label: "NL - Netherlands" },
  { value: "CA", label: "CA - Canada" },
  { value: "AU", label: "AU - Australia" },
  { value: "IN", label: "IN - India" },
  { value: "PK", label: "PK - Pakistan" },
  { value: "CN", label: "CN - China" },
  { value: "JP", label: "JP - Japan" },
];

export const PLAN_REGION_OPTIONS: SearchableSelectOption[] = [
  { value: "MENA", label: "MENA - Middle East and North Africa" },
  { value: "GCC", label: "GCC - Gulf Cooperation Council" },
  { value: "EMEA", label: "EMEA - Europe, Middle East, and Africa" },
  { value: "EU", label: "EU - European Union" },
  { value: "APAC", label: "APAC - Asia-Pacific" },
  { value: "ASEAN", label: "ASEAN - Southeast Asia" },
  { value: "NA", label: "NA - North America" },
  { value: "LATAM", label: "LATAM - Latin America" },
  { value: "SSA", label: "SSA - Sub-Saharan Africa" },
];
