import { useMutation, useQuery } from "@tanstack/react-query";
import { z } from "zod";
import { apiClient, type components } from "@/shared/api";

/** Immutable sender boundary assigned to a registered Email Type. */
export type EmailContext = components["schemas"]["EmailContext"];
/** Locale supported by the backend email registry. */
export type EmailLocale = components["schemas"]["EmailLocale"];
/** Registered Email Type generated from the backend OpenAPI contract. */
export type EmailType = components["schemas"]["EmailType"];
/** Catalog response generated from the backend OpenAPI contract. */
export type EmailTypeListResponse = components["schemas"]["EmailTypeListResponse"];
/** Safe sample preview generated by the backend. */
export type EmailPreview = components["schemas"]["EmailPreview"];
/** Durable queue acceptance returned for a platform test email. */
export type TestSendResponse = components["schemas"]["TestSendResponse"];

const EMAIL_CONTEXTS = ["EDARA", "COMPANY"] as const satisfies readonly EmailContext[];
const EMAIL_LOCALES = ["en", "ar"] as const satisfies readonly EmailLocale[];
const EMAIL_PREVIEW_SCHEMA: z.ZodType<EmailPreview> = z.object({
  emailTypeKey: z.string().min(1),
  templateKey: z.string().min(1),
  context: z.enum(EMAIL_CONTEXTS),
  locale: z.enum(EMAIL_LOCALES),
  subject: z.string(),
  preheader: z.string(),
  html: z.string(),
  text: z.string(),
  senderIdentity: z
    .object({
      name: z.string().min(1),
      address: z.string().email(),
      replyTo: z.string().email(),
    })
    .optional(),
});
const TEST_SEND_RESPONSE_SCHEMA: z.ZodType<TestSendResponse> = z.object({
  publicId: z.string().uuid(),
  status: z.enum(["QUEUED", "PROCESSING", "RETRY_SCHEDULED", "SENT", "FAILED", "CANCELLED"]),
  emailTypeKey: z.string().min(1),
  context: z.enum(EMAIL_CONTEXTS),
  locale: z.enum(EMAIL_LOCALES),
  isTest: z.literal(true),
});

interface QueueTestSendInput {
  emailType: EmailType;
  locale: EmailLocale;
  recipientEmail: string;
}

const EMAIL_PLATFORM_KEYS = {
  catalog: () => ["email-platform", "catalog"] as const,
  preview: (emailType: EmailType | undefined, locale: EmailLocale) =>
    [
      "email-platform",
      "preview",
      emailType?.key ?? "",
      emailType?.defaultTemplateKey ?? "",
      emailType?.context ?? "",
      locale,
    ] as const,
};

async function fetchEmailTypes(): Promise<EmailTypeListResponse> {
  return apiClient.get("email-types").json<EmailTypeListResponse>();
}

async function fetchEmailPreview(emailType: EmailType, locale: EmailLocale): Promise<EmailPreview> {
  const response = await apiClient
    .get(`email-types/${emailType.key}/preview`, { searchParams: { locale } })
    .json<unknown>();
  const preview = EMAIL_PREVIEW_SCHEMA.parse(response);
  const responseMatchesRequest =
    preview.emailTypeKey === emailType.key &&
    preview.templateKey === emailType.defaultTemplateKey &&
    preview.context === emailType.context &&
    (emailType.context !== "COMPANY" || preview.senderIdentity !== undefined);

  if (!responseMatchesRequest) throw new Error("Invalid email preview response");
  return preview;
}

async function queueTestSend({ emailType, locale, recipientEmail }: QueueTestSendInput) {
  const response = await apiClient
    .post("emails/test-send", {
      json: { emailTypeKey: emailType.key, locale, recipientEmail },
    })
    .json<unknown>();
  const queuedTestSend = TEST_SEND_RESPONSE_SCHEMA.parse(response);

  if (
    queuedTestSend.emailTypeKey !== emailType.key ||
    queuedTestSend.context !== emailType.context
  ) {
    throw new Error("Invalid test email response");
  }

  return queuedTestSend;
}

/** Loads the immutable Email Type catalog. */
export function useEmailTypes() {
  return useQuery({
    queryKey: EMAIL_PLATFORM_KEYS.catalog(),
    queryFn: fetchEmailTypes,
  });
}

/** Loads a secret-safe sample preview for one registered Email Type and locale. */
export function useEmailPreview(emailType: EmailType | undefined, locale: EmailLocale) {
  return useQuery({
    queryKey: EMAIL_PLATFORM_KEYS.preview(emailType, locale),
    queryFn: () => {
      if (!emailType) throw new Error("Email Type is required for preview");
      return fetchEmailPreview(emailType, locale);
    },
    enabled: emailType !== undefined,
  });
}

/** Queues a platform test email using the selected effective locale. */
export function useQueueEmailTestSend() {
  return useMutation({ mutationFn: queueTestSend });
}
