import type { SupportedLocale } from "@/shared/i18n";

const auditCopy = {
  en: {
    anonymous: "Anonymous",
    attributionFailed: "Attribution failed",
    erasedIdentity: "Erased identity",
    system: "System",
    platformAdmin: "Platform admin",
    identityWithheld: "Identity withheld",
    failure: "Failure",
    changedTo: "changed to",
    changedFields: "Changed fields",
    recordedAt: "Recorded at",
    targets: "Targets",
    origin: "Origin",
    ip: "IP",
    userAgent: "User agent",
    none: "None",
    yes: "Yes",
    no: "No",
    unableToDisplay: "Unable to display value",
    company: "Company",
    platform: "Platform",
    noAdditionalDetails: "No additional details",
    density: "Density",
    comfortable: "Comfortable",
    compact: "Compact",
    unrecognizedEvent: "Unrecognized event",
    unavailableEvent: "Unavailable event",
    portalGap: "Portal gap",
    degradedTitle: "This record exists, but this portal cannot display its payload yet.",
    degradedDescription: "The gap belongs to the portal, not the audit trail.",
    unknownEvent: "unknown event",
    unknownTime: "Unknown time",
  },
  ar: {
    anonymous: "مجهول الهوية",
    attributionFailed: "تعذر تحديد الهوية",
    erasedIdentity: "هوية محذوفة",
    system: "النظام",
    platformAdmin: "مسؤول المنصة",
    identityWithheld: "الهوية محجوبة",
    failure: "فشل",
    changedTo: "تغير إلى",
    changedFields: "الحقول المتغيرة",
    recordedAt: "سُجل في",
    targets: "الأهداف",
    origin: "المصدر",
    ip: "عنوان IP",
    userAgent: "وكيل المستخدم",
    none: "لا يوجد",
    yes: "نعم",
    no: "لا",
    unableToDisplay: "تعذر عرض القيمة",
    company: "الشركة",
    platform: "المنصة",
    noAdditionalDetails: "لا توجد تفاصيل إضافية",
    density: "الكثافة",
    comfortable: "مريح",
    compact: "مضغوط",
    unrecognizedEvent: "حدث غير معروف",
    unavailableEvent: "حدث غير متاح",
    portalGap: "فجوة في البوابة",
    degradedTitle: "السجل موجود، لكن هذه البوابة لا تستطيع عرض بياناته بعد.",
    degradedDescription: "الفجوة في البوابة وليست في سجل التدقيق.",
    unknownEvent: "حدث غير معروف",
    unknownTime: "وقت غير معروف",
  },
} as const;

export function getAuditCopy(locale: SupportedLocale) {
  return auditCopy[locale];
}
