// Generated by scripts/generate-audit-label-keys.mjs from contracts/openapi.json.
// Do not edit this file directly.

/**
 * The audit detail fields the contract closes to a fixed set of values. A field listed
 * here renders through the enum formatter, so a value the contract adds later reads as
 * words rather than as a raw token.
 */
export const auditEnumFields: readonly string[] = [
  "afterStatus",
  "beforeStatus",
  "effectiveMode",
  "mode",
  "operation",
  "previousMode",
  "scope",
  "status",
  "stepType",
];
