/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/routes/__root"
import { Route as CompanyRouteRouteImport } from "./app/routes/company/route"
import { Route as AdminRouteRouteImport } from "./app/routes/admin/route"
import { Route as IndexRouteImport } from "./app/routes/index"
import { Route as ResetPasswordIndexRouteImport } from "./app/routes/reset-password/index"
import { Route as LoginIndexRouteImport } from "./app/routes/login/index"
import { Route as ForgotPasswordIndexRouteImport } from "./app/routes/forgot-password/index"
import { Route as ForbiddenIndexRouteImport } from "./app/routes/forbidden/index"
import { Route as ChangePasswordIndexRouteImport } from "./app/routes/change-password/index"
import { Route as AdminIndexRouteImport } from "./app/routes/admin/index"
import { Route as AcceptInvitationIndexRouteImport } from "./app/routes/accept-invitation/index"
import { Route as ForgotPasswordSentRouteImport } from "./app/routes/forgot-password/sent"
import { Route as AdminLoginRouteImport } from "./app/routes/admin_/login"
import { Route as AdminLeadsRouteRouteImport } from "./app/routes/admin/leads/route"
import { Route as AdminCompaniesRouteRouteImport } from "./app/routes/admin/companies/route"
import { Route as CompanySetupIndexRouteImport } from "./app/routes/company/setup/index"
import { Route as CompanyProfileIndexRouteImport } from "./app/routes/company/profile/index"
import { Route as CompanyEmailSettingsIndexRouteImport } from "./app/routes/company/email-settings/index"
import { Route as CompanyDashboardIndexRouteImport } from "./app/routes/company/dashboard/index"
import { Route as CompanyAuditIndexRouteImport } from "./app/routes/company/audit/index"
import { Route as AdminResetPasswordIndexRouteImport } from "./app/routes/admin_/reset-password/index"
import { Route as AdminForgotPasswordIndexRouteImport } from "./app/routes/admin_/forgot-password/index"
import { Route as AdminSubscriptionsIndexRouteImport } from "./app/routes/admin/subscriptions/index"
import { Route as AdminPlansIndexRouteImport } from "./app/routes/admin/plans/index"
import { Route as AdminLeadsIndexRouteImport } from "./app/routes/admin/leads/index"
import { Route as AdminEmailIndexRouteImport } from "./app/routes/admin/email/index"
import { Route as AdminDashboardIndexRouteImport } from "./app/routes/admin/dashboard/index"
import { Route as AdminConversionRequestsIndexRouteImport } from "./app/routes/admin/conversion-requests/index"
import { Route as AdminCompaniesIndexRouteImport } from "./app/routes/admin/companies/index"
import { Route as AdminAuditIndexRouteImport } from "./app/routes/admin/audit/index"
import { Route as AdminForgotPasswordSentRouteImport } from "./app/routes/admin_/forgot-password/sent"
import { Route as AdminLeadsPublicIdRouteImport } from "./app/routes/admin/leads/$publicId"
import { Route as AdminEmailSendingRouteImport } from "./app/routes/admin/email/sending"
import { Route as AdminEmailDeliveriesRouteImport } from "./app/routes/admin/email/deliveries"
import { Route as AdminConversionRequestsPublicIdRouteImport } from "./app/routes/admin/conversion-requests/$publicId"
import { Route as AdminAuditCatalogRouteImport } from "./app/routes/admin/audit/catalog"
import { Route as AdminCompaniesPublicIdRouteRouteImport } from "./app/routes/admin/companies/$publicId/route"
import { Route as AdminCompaniesPublicIdIndexRouteImport } from "./app/routes/admin/companies/$publicId/index"
import { Route as AdminCompaniesPublicIdEmailSettingsRouteImport } from "./app/routes/admin/companies/$publicId/email-settings"

const CompanyRouteRoute = CompanyRouteRouteImport.update({
  id: "/company",
  path: "/company",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: "/reset-password/",
  path: "/reset-password/",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: "/forgot-password/",
  path: "/forgot-password/",
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenIndexRoute = ForbiddenIndexRouteImport.update({
  id: "/forbidden/",
  path: "/forbidden/",
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordIndexRoute = ChangePasswordIndexRouteImport.update({
  id: "/change-password/",
  path: "/change-password/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AcceptInvitationIndexRoute = AcceptInvitationIndexRouteImport.update({
  id: "/accept-invitation/",
  path: "/accept-invitation/",
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordSentRoute = ForgotPasswordSentRouteImport.update({
  id: "/forgot-password/sent",
  path: "/forgot-password/sent",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: "/admin_/login",
  path: "/admin/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRouteRoute = AdminLeadsRouteRouteImport.update({
  id: "/leads",
  path: "/leads",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCompaniesRouteRoute = AdminCompaniesRouteRouteImport.update({
  id: "/companies",
  path: "/companies",
  getParentRoute: () => AdminRouteRoute,
} as any)
const CompanySetupIndexRoute = CompanySetupIndexRouteImport.update({
  id: "/setup/",
  path: "/setup/",
  getParentRoute: () => CompanyRouteRoute,
} as any)
const CompanyProfileIndexRoute = CompanyProfileIndexRouteImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => CompanyRouteRoute,
} as any)
const CompanyEmailSettingsIndexRoute =
  CompanyEmailSettingsIndexRouteImport.update({
    id: "/email-settings/",
    path: "/email-settings/",
    getParentRoute: () => CompanyRouteRoute,
  } as any)
const CompanyDashboardIndexRoute = CompanyDashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => CompanyRouteRoute,
} as any)
const CompanyAuditIndexRoute = CompanyAuditIndexRouteImport.update({
  id: "/audit/",
  path: "/audit/",
  getParentRoute: () => CompanyRouteRoute,
} as any)
const AdminResetPasswordIndexRoute = AdminResetPasswordIndexRouteImport.update({
  id: "/admin_/reset-password/",
  path: "/admin/reset-password/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordIndexRoute =
  AdminForgotPasswordIndexRouteImport.update({
    id: "/admin_/forgot-password/",
    path: "/admin/forgot-password/",
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSubscriptionsIndexRoute = AdminSubscriptionsIndexRouteImport.update({
  id: "/subscriptions/",
  path: "/subscriptions/",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlansIndexRoute = AdminPlansIndexRouteImport.update({
  id: "/plans/",
  path: "/plans/",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminLeadsRouteRoute,
} as any)
const AdminEmailIndexRoute = AdminEmailIndexRouteImport.update({
  id: "/email/",
  path: "/email/",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConversionRequestsIndexRoute =
  AdminConversionRequestsIndexRouteImport.update({
    id: "/conversion-requests/",
    path: "/conversion-requests/",
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminCompaniesRouteRoute,
} as any)
const AdminAuditIndexRoute = AdminAuditIndexRouteImport.update({
  id: "/audit/",
  path: "/audit/",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminForgotPasswordSentRoute = AdminForgotPasswordSentRouteImport.update({
  id: "/admin_/forgot-password/sent",
  path: "/admin/forgot-password/sent",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsPublicIdRoute = AdminLeadsPublicIdRouteImport.update({
  id: "/$publicId",
  path: "/$publicId",
  getParentRoute: () => AdminLeadsRouteRoute,
} as any)
const AdminEmailSendingRoute = AdminEmailSendingRouteImport.update({
  id: "/email/sending",
  path: "/email/sending",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmailDeliveriesRoute = AdminEmailDeliveriesRouteImport.update({
  id: "/email/deliveries",
  path: "/email/deliveries",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminConversionRequestsPublicIdRoute =
  AdminConversionRequestsPublicIdRouteImport.update({
    id: "/conversion-requests/$publicId",
    path: "/conversion-requests/$publicId",
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAuditCatalogRoute = AdminAuditCatalogRouteImport.update({
  id: "/audit/catalog",
  path: "/audit/catalog",
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCompaniesPublicIdRouteRoute =
  AdminCompaniesPublicIdRouteRouteImport.update({
    id: "/$publicId",
    path: "/$publicId",
    getParentRoute: () => AdminCompaniesRouteRoute,
  } as any)
const AdminCompaniesPublicIdIndexRoute =
  AdminCompaniesPublicIdIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AdminCompaniesPublicIdRouteRoute,
  } as any)
const AdminCompaniesPublicIdEmailSettingsRoute =
  AdminCompaniesPublicIdEmailSettingsRouteImport.update({
    id: "/email-settings",
    path: "/email-settings",
    getParentRoute: () => AdminCompaniesPublicIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteRouteWithChildren
  "/company": typeof CompanyRouteRouteWithChildren
  "/admin/companies": typeof AdminCompaniesRouteRouteWithChildren
  "/admin/leads": typeof AdminLeadsRouteRouteWithChildren
  "/admin/login": typeof AdminLoginRoute
  "/forgot-password/sent": typeof ForgotPasswordSentRoute
  "/accept-invitation/": typeof AcceptInvitationIndexRoute
  "/admin/": typeof AdminIndexRoute
  "/change-password/": typeof ChangePasswordIndexRoute
  "/forbidden/": typeof ForbiddenIndexRoute
  "/forgot-password/": typeof ForgotPasswordIndexRoute
  "/login/": typeof LoginIndexRoute
  "/reset-password/": typeof ResetPasswordIndexRoute
  "/admin/companies/$publicId": typeof AdminCompaniesPublicIdRouteRouteWithChildren
  "/admin/audit/catalog": typeof AdminAuditCatalogRoute
  "/admin/conversion-requests/$publicId": typeof AdminConversionRequestsPublicIdRoute
  "/admin/email/deliveries": typeof AdminEmailDeliveriesRoute
  "/admin/email/sending": typeof AdminEmailSendingRoute
  "/admin/leads/$publicId": typeof AdminLeadsPublicIdRoute
  "/admin/forgot-password/sent": typeof AdminForgotPasswordSentRoute
  "/admin/audit/": typeof AdminAuditIndexRoute
  "/admin/companies/": typeof AdminCompaniesIndexRoute
  "/admin/conversion-requests/": typeof AdminConversionRequestsIndexRoute
  "/admin/dashboard/": typeof AdminDashboardIndexRoute
  "/admin/email/": typeof AdminEmailIndexRoute
  "/admin/leads/": typeof AdminLeadsIndexRoute
  "/admin/plans/": typeof AdminPlansIndexRoute
  "/admin/subscriptions/": typeof AdminSubscriptionsIndexRoute
  "/admin/forgot-password/": typeof AdminForgotPasswordIndexRoute
  "/admin/reset-password/": typeof AdminResetPasswordIndexRoute
  "/company/audit/": typeof CompanyAuditIndexRoute
  "/company/dashboard/": typeof CompanyDashboardIndexRoute
  "/company/email-settings/": typeof CompanyEmailSettingsIndexRoute
  "/company/profile/": typeof CompanyProfileIndexRoute
  "/company/setup/": typeof CompanySetupIndexRoute
  "/admin/companies/$publicId/email-settings": typeof AdminCompaniesPublicIdEmailSettingsRoute
  "/admin/companies/$publicId/": typeof AdminCompaniesPublicIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/company": typeof CompanyRouteRouteWithChildren
  "/admin/login": typeof AdminLoginRoute
  "/forgot-password/sent": typeof ForgotPasswordSentRoute
  "/accept-invitation": typeof AcceptInvitationIndexRoute
  "/admin": typeof AdminIndexRoute
  "/change-password": typeof ChangePasswordIndexRoute
  "/forbidden": typeof ForbiddenIndexRoute
  "/forgot-password": typeof ForgotPasswordIndexRoute
  "/login": typeof LoginIndexRoute
  "/reset-password": typeof ResetPasswordIndexRoute
  "/admin/audit/catalog": typeof AdminAuditCatalogRoute
  "/admin/conversion-requests/$publicId": typeof AdminConversionRequestsPublicIdRoute
  "/admin/email/deliveries": typeof AdminEmailDeliveriesRoute
  "/admin/email/sending": typeof AdminEmailSendingRoute
  "/admin/leads/$publicId": typeof AdminLeadsPublicIdRoute
  "/admin/forgot-password/sent": typeof AdminForgotPasswordSentRoute
  "/admin/audit": typeof AdminAuditIndexRoute
  "/admin/companies": typeof AdminCompaniesIndexRoute
  "/admin/conversion-requests": typeof AdminConversionRequestsIndexRoute
  "/admin/dashboard": typeof AdminDashboardIndexRoute
  "/admin/email": typeof AdminEmailIndexRoute
  "/admin/leads": typeof AdminLeadsIndexRoute
  "/admin/plans": typeof AdminPlansIndexRoute
  "/admin/subscriptions": typeof AdminSubscriptionsIndexRoute
  "/admin/forgot-password": typeof AdminForgotPasswordIndexRoute
  "/admin/reset-password": typeof AdminResetPasswordIndexRoute
  "/company/audit": typeof CompanyAuditIndexRoute
  "/company/dashboard": typeof CompanyDashboardIndexRoute
  "/company/email-settings": typeof CompanyEmailSettingsIndexRoute
  "/company/profile": typeof CompanyProfileIndexRoute
  "/company/setup": typeof CompanySetupIndexRoute
  "/admin/companies/$publicId/email-settings": typeof AdminCompaniesPublicIdEmailSettingsRoute
  "/admin/companies/$publicId": typeof AdminCompaniesPublicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/admin": typeof AdminRouteRouteWithChildren
  "/company": typeof CompanyRouteRouteWithChildren
  "/admin/companies": typeof AdminCompaniesRouteRouteWithChildren
  "/admin/leads": typeof AdminLeadsRouteRouteWithChildren
  "/admin_/login": typeof AdminLoginRoute
  "/forgot-password/sent": typeof ForgotPasswordSentRoute
  "/accept-invitation/": typeof AcceptInvitationIndexRoute
  "/admin/": typeof AdminIndexRoute
  "/change-password/": typeof ChangePasswordIndexRoute
  "/forbidden/": typeof ForbiddenIndexRoute
  "/forgot-password/": typeof ForgotPasswordIndexRoute
  "/login/": typeof LoginIndexRoute
  "/reset-password/": typeof ResetPasswordIndexRoute
  "/admin/companies/$publicId": typeof AdminCompaniesPublicIdRouteRouteWithChildren
  "/admin/audit/catalog": typeof AdminAuditCatalogRoute
  "/admin/conversion-requests/$publicId": typeof AdminConversionRequestsPublicIdRoute
  "/admin/email/deliveries": typeof AdminEmailDeliveriesRoute
  "/admin/email/sending": typeof AdminEmailSendingRoute
  "/admin/leads/$publicId": typeof AdminLeadsPublicIdRoute
  "/admin_/forgot-password/sent": typeof AdminForgotPasswordSentRoute
  "/admin/audit/": typeof AdminAuditIndexRoute
  "/admin/companies/": typeof AdminCompaniesIndexRoute
  "/admin/conversion-requests/": typeof AdminConversionRequestsIndexRoute
  "/admin/dashboard/": typeof AdminDashboardIndexRoute
  "/admin/email/": typeof AdminEmailIndexRoute
  "/admin/leads/": typeof AdminLeadsIndexRoute
  "/admin/plans/": typeof AdminPlansIndexRoute
  "/admin/subscriptions/": typeof AdminSubscriptionsIndexRoute
  "/admin_/forgot-password/": typeof AdminForgotPasswordIndexRoute
  "/admin_/reset-password/": typeof AdminResetPasswordIndexRoute
  "/company/audit/": typeof CompanyAuditIndexRoute
  "/company/dashboard/": typeof CompanyDashboardIndexRoute
  "/company/email-settings/": typeof CompanyEmailSettingsIndexRoute
  "/company/profile/": typeof CompanyProfileIndexRoute
  "/company/setup/": typeof CompanySetupIndexRoute
  "/admin/companies/$publicId/email-settings": typeof AdminCompaniesPublicIdEmailSettingsRoute
  "/admin/companies/$publicId/": typeof AdminCompaniesPublicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/company"
    | "/admin/companies"
    | "/admin/leads"
    | "/admin/login"
    | "/forgot-password/sent"
    | "/accept-invitation/"
    | "/admin/"
    | "/change-password/"
    | "/forbidden/"
    | "/forgot-password/"
    | "/login/"
    | "/reset-password/"
    | "/admin/companies/$publicId"
    | "/admin/audit/catalog"
    | "/admin/conversion-requests/$publicId"
    | "/admin/email/deliveries"
    | "/admin/email/sending"
    | "/admin/leads/$publicId"
    | "/admin/forgot-password/sent"
    | "/admin/audit/"
    | "/admin/companies/"
    | "/admin/conversion-requests/"
    | "/admin/dashboard/"
    | "/admin/email/"
    | "/admin/leads/"
    | "/admin/plans/"
    | "/admin/subscriptions/"
    | "/admin/forgot-password/"
    | "/admin/reset-password/"
    | "/company/audit/"
    | "/company/dashboard/"
    | "/company/email-settings/"
    | "/company/profile/"
    | "/company/setup/"
    | "/admin/companies/$publicId/email-settings"
    | "/admin/companies/$publicId/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/company"
    | "/admin/login"
    | "/forgot-password/sent"
    | "/accept-invitation"
    | "/admin"
    | "/change-password"
    | "/forbidden"
    | "/forgot-password"
    | "/login"
    | "/reset-password"
    | "/admin/audit/catalog"
    | "/admin/conversion-requests/$publicId"
    | "/admin/email/deliveries"
    | "/admin/email/sending"
    | "/admin/leads/$publicId"
    | "/admin/forgot-password/sent"
    | "/admin/audit"
    | "/admin/companies"
    | "/admin/conversion-requests"
    | "/admin/dashboard"
    | "/admin/email"
    | "/admin/leads"
    | "/admin/plans"
    | "/admin/subscriptions"
    | "/admin/forgot-password"
    | "/admin/reset-password"
    | "/company/audit"
    | "/company/dashboard"
    | "/company/email-settings"
    | "/company/profile"
    | "/company/setup"
    | "/admin/companies/$publicId/email-settings"
    | "/admin/companies/$publicId"
  id:
    | "__root__"
    | "/"
    | "/admin"
    | "/company"
    | "/admin/companies"
    | "/admin/leads"
    | "/admin_/login"
    | "/forgot-password/sent"
    | "/accept-invitation/"
    | "/admin/"
    | "/change-password/"
    | "/forbidden/"
    | "/forgot-password/"
    | "/login/"
    | "/reset-password/"
    | "/admin/companies/$publicId"
    | "/admin/audit/catalog"
    | "/admin/conversion-requests/$publicId"
    | "/admin/email/deliveries"
    | "/admin/email/sending"
    | "/admin/leads/$publicId"
    | "/admin_/forgot-password/sent"
    | "/admin/audit/"
    | "/admin/companies/"
    | "/admin/conversion-requests/"
    | "/admin/dashboard/"
    | "/admin/email/"
    | "/admin/leads/"
    | "/admin/plans/"
    | "/admin/subscriptions/"
    | "/admin_/forgot-password/"
    | "/admin_/reset-password/"
    | "/company/audit/"
    | "/company/dashboard/"
    | "/company/email-settings/"
    | "/company/profile/"
    | "/company/setup/"
    | "/admin/companies/$publicId/email-settings"
    | "/admin/companies/$publicId/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CompanyRouteRoute: typeof CompanyRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ForgotPasswordSentRoute: typeof ForgotPasswordSentRoute
  AcceptInvitationIndexRoute: typeof AcceptInvitationIndexRoute
  ChangePasswordIndexRoute: typeof ChangePasswordIndexRoute
  ForbiddenIndexRoute: typeof ForbiddenIndexRoute
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  AdminForgotPasswordSentRoute: typeof AdminForgotPasswordSentRoute
  AdminForgotPasswordIndexRoute: typeof AdminForgotPasswordIndexRoute
  AdminResetPasswordIndexRoute: typeof AdminResetPasswordIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/company": {
      id: "/company"
      path: "/company"
      fullPath: "/company"
      preLoaderRoute: typeof CompanyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/reset-password/": {
      id: "/reset-password/"
      path: "/reset-password"
      fullPath: "/reset-password/"
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login/": {
      id: "/login/"
      path: "/login"
      fullPath: "/login/"
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password/": {
      id: "/forgot-password/"
      path: "/forgot-password"
      fullPath: "/forgot-password/"
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forbidden/": {
      id: "/forbidden/"
      path: "/forbidden"
      fullPath: "/forbidden/"
      preLoaderRoute: typeof ForbiddenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/change-password/": {
      id: "/change-password/"
      path: "/change-password"
      fullPath: "/change-password/"
      preLoaderRoute: typeof ChangePasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/accept-invitation/": {
      id: "/accept-invitation/"
      path: "/accept-invitation"
      fullPath: "/accept-invitation/"
      preLoaderRoute: typeof AcceptInvitationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forgot-password/sent": {
      id: "/forgot-password/sent"
      path: "/forgot-password/sent"
      fullPath: "/forgot-password/sent"
      preLoaderRoute: typeof ForgotPasswordSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin_/login": {
      id: "/admin_/login"
      path: "/admin/login"
      fullPath: "/admin/login"
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/leads": {
      id: "/admin/leads"
      path: "/leads"
      fullPath: "/admin/leads"
      preLoaderRoute: typeof AdminLeadsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/companies": {
      id: "/admin/companies"
      path: "/companies"
      fullPath: "/admin/companies"
      preLoaderRoute: typeof AdminCompaniesRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/company/setup/": {
      id: "/company/setup/"
      path: "/setup"
      fullPath: "/company/setup/"
      preLoaderRoute: typeof CompanySetupIndexRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    "/company/profile/": {
      id: "/company/profile/"
      path: "/profile"
      fullPath: "/company/profile/"
      preLoaderRoute: typeof CompanyProfileIndexRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    "/company/email-settings/": {
      id: "/company/email-settings/"
      path: "/email-settings"
      fullPath: "/company/email-settings/"
      preLoaderRoute: typeof CompanyEmailSettingsIndexRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    "/company/dashboard/": {
      id: "/company/dashboard/"
      path: "/dashboard"
      fullPath: "/company/dashboard/"
      preLoaderRoute: typeof CompanyDashboardIndexRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    "/company/audit/": {
      id: "/company/audit/"
      path: "/audit"
      fullPath: "/company/audit/"
      preLoaderRoute: typeof CompanyAuditIndexRouteImport
      parentRoute: typeof CompanyRouteRoute
    }
    "/admin_/reset-password/": {
      id: "/admin_/reset-password/"
      path: "/admin/reset-password"
      fullPath: "/admin/reset-password/"
      preLoaderRoute: typeof AdminResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin_/forgot-password/": {
      id: "/admin_/forgot-password/"
      path: "/admin/forgot-password"
      fullPath: "/admin/forgot-password/"
      preLoaderRoute: typeof AdminForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/subscriptions/": {
      id: "/admin/subscriptions/"
      path: "/subscriptions"
      fullPath: "/admin/subscriptions/"
      preLoaderRoute: typeof AdminSubscriptionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/plans/": {
      id: "/admin/plans/"
      path: "/plans"
      fullPath: "/admin/plans/"
      preLoaderRoute: typeof AdminPlansIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/leads/": {
      id: "/admin/leads/"
      path: "/"
      fullPath: "/admin/leads/"
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminLeadsRouteRoute
    }
    "/admin/email/": {
      id: "/admin/email/"
      path: "/email"
      fullPath: "/admin/email/"
      preLoaderRoute: typeof AdminEmailIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/dashboard/": {
      id: "/admin/dashboard/"
      path: "/dashboard"
      fullPath: "/admin/dashboard/"
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/conversion-requests/": {
      id: "/admin/conversion-requests/"
      path: "/conversion-requests"
      fullPath: "/admin/conversion-requests/"
      preLoaderRoute: typeof AdminConversionRequestsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/companies/": {
      id: "/admin/companies/"
      path: "/"
      fullPath: "/admin/companies/"
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof AdminCompaniesRouteRoute
    }
    "/admin/audit/": {
      id: "/admin/audit/"
      path: "/audit"
      fullPath: "/admin/audit/"
      preLoaderRoute: typeof AdminAuditIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin_/forgot-password/sent": {
      id: "/admin_/forgot-password/sent"
      path: "/admin/forgot-password/sent"
      fullPath: "/admin/forgot-password/sent"
      preLoaderRoute: typeof AdminForgotPasswordSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/leads/$publicId": {
      id: "/admin/leads/$publicId"
      path: "/$publicId"
      fullPath: "/admin/leads/$publicId"
      preLoaderRoute: typeof AdminLeadsPublicIdRouteImport
      parentRoute: typeof AdminLeadsRouteRoute
    }
    "/admin/email/sending": {
      id: "/admin/email/sending"
      path: "/email/sending"
      fullPath: "/admin/email/sending"
      preLoaderRoute: typeof AdminEmailSendingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/email/deliveries": {
      id: "/admin/email/deliveries"
      path: "/email/deliveries"
      fullPath: "/admin/email/deliveries"
      preLoaderRoute: typeof AdminEmailDeliveriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/conversion-requests/$publicId": {
      id: "/admin/conversion-requests/$publicId"
      path: "/conversion-requests/$publicId"
      fullPath: "/admin/conversion-requests/$publicId"
      preLoaderRoute: typeof AdminConversionRequestsPublicIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/audit/catalog": {
      id: "/admin/audit/catalog"
      path: "/audit/catalog"
      fullPath: "/admin/audit/catalog"
      preLoaderRoute: typeof AdminAuditCatalogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    "/admin/companies/$publicId": {
      id: "/admin/companies/$publicId"
      path: "/$publicId"
      fullPath: "/admin/companies/$publicId"
      preLoaderRoute: typeof AdminCompaniesPublicIdRouteRouteImport
      parentRoute: typeof AdminCompaniesRouteRoute
    }
    "/admin/companies/$publicId/": {
      id: "/admin/companies/$publicId/"
      path: "/"
      fullPath: "/admin/companies/$publicId/"
      preLoaderRoute: typeof AdminCompaniesPublicIdIndexRouteImport
      parentRoute: typeof AdminCompaniesPublicIdRouteRoute
    }
    "/admin/companies/$publicId/email-settings": {
      id: "/admin/companies/$publicId/email-settings"
      path: "/email-settings"
      fullPath: "/admin/companies/$publicId/email-settings"
      preLoaderRoute: typeof AdminCompaniesPublicIdEmailSettingsRouteImport
      parentRoute: typeof AdminCompaniesPublicIdRouteRoute
    }
  }
}

interface AdminCompaniesPublicIdRouteRouteChildren {
  AdminCompaniesPublicIdEmailSettingsRoute: typeof AdminCompaniesPublicIdEmailSettingsRoute
  AdminCompaniesPublicIdIndexRoute: typeof AdminCompaniesPublicIdIndexRoute
}

const AdminCompaniesPublicIdRouteRouteChildren: AdminCompaniesPublicIdRouteRouteChildren =
  {
    AdminCompaniesPublicIdEmailSettingsRoute:
      AdminCompaniesPublicIdEmailSettingsRoute,
    AdminCompaniesPublicIdIndexRoute: AdminCompaniesPublicIdIndexRoute,
  }

const AdminCompaniesPublicIdRouteRouteWithChildren =
  AdminCompaniesPublicIdRouteRoute._addFileChildren(
    AdminCompaniesPublicIdRouteRouteChildren,
  )

interface AdminCompaniesRouteRouteChildren {
  AdminCompaniesPublicIdRouteRoute: typeof AdminCompaniesPublicIdRouteRouteWithChildren
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
}

const AdminCompaniesRouteRouteChildren: AdminCompaniesRouteRouteChildren = {
  AdminCompaniesPublicIdRouteRoute:
    AdminCompaniesPublicIdRouteRouteWithChildren,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
}

const AdminCompaniesRouteRouteWithChildren =
  AdminCompaniesRouteRoute._addFileChildren(AdminCompaniesRouteRouteChildren)

interface AdminLeadsRouteRouteChildren {
  AdminLeadsPublicIdRoute: typeof AdminLeadsPublicIdRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
}

const AdminLeadsRouteRouteChildren: AdminLeadsRouteRouteChildren = {
  AdminLeadsPublicIdRoute: AdminLeadsPublicIdRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
}

const AdminLeadsRouteRouteWithChildren = AdminLeadsRouteRoute._addFileChildren(
  AdminLeadsRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCompaniesRouteRoute: typeof AdminCompaniesRouteRouteWithChildren
  AdminLeadsRouteRoute: typeof AdminLeadsRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAuditCatalogRoute: typeof AdminAuditCatalogRoute
  AdminConversionRequestsPublicIdRoute: typeof AdminConversionRequestsPublicIdRoute
  AdminEmailDeliveriesRoute: typeof AdminEmailDeliveriesRoute
  AdminEmailSendingRoute: typeof AdminEmailSendingRoute
  AdminAuditIndexRoute: typeof AdminAuditIndexRoute
  AdminConversionRequestsIndexRoute: typeof AdminConversionRequestsIndexRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  AdminEmailIndexRoute: typeof AdminEmailIndexRoute
  AdminPlansIndexRoute: typeof AdminPlansIndexRoute
  AdminSubscriptionsIndexRoute: typeof AdminSubscriptionsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCompaniesRouteRoute: AdminCompaniesRouteRouteWithChildren,
  AdminLeadsRouteRoute: AdminLeadsRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminAuditCatalogRoute: AdminAuditCatalogRoute,
  AdminConversionRequestsPublicIdRoute: AdminConversionRequestsPublicIdRoute,
  AdminEmailDeliveriesRoute: AdminEmailDeliveriesRoute,
  AdminEmailSendingRoute: AdminEmailSendingRoute,
  AdminAuditIndexRoute: AdminAuditIndexRoute,
  AdminConversionRequestsIndexRoute: AdminConversionRequestsIndexRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  AdminEmailIndexRoute: AdminEmailIndexRoute,
  AdminPlansIndexRoute: AdminPlansIndexRoute,
  AdminSubscriptionsIndexRoute: AdminSubscriptionsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface CompanyRouteRouteChildren {
  CompanyAuditIndexRoute: typeof CompanyAuditIndexRoute
  CompanyDashboardIndexRoute: typeof CompanyDashboardIndexRoute
  CompanyEmailSettingsIndexRoute: typeof CompanyEmailSettingsIndexRoute
  CompanyProfileIndexRoute: typeof CompanyProfileIndexRoute
  CompanySetupIndexRoute: typeof CompanySetupIndexRoute
}

const CompanyRouteRouteChildren: CompanyRouteRouteChildren = {
  CompanyAuditIndexRoute: CompanyAuditIndexRoute,
  CompanyDashboardIndexRoute: CompanyDashboardIndexRoute,
  CompanyEmailSettingsIndexRoute: CompanyEmailSettingsIndexRoute,
  CompanyProfileIndexRoute: CompanyProfileIndexRoute,
  CompanySetupIndexRoute: CompanySetupIndexRoute,
}

const CompanyRouteRouteWithChildren = CompanyRouteRoute._addFileChildren(
  CompanyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CompanyRouteRoute: CompanyRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ForgotPasswordSentRoute: ForgotPasswordSentRoute,
  AcceptInvitationIndexRoute: AcceptInvitationIndexRoute,
  ChangePasswordIndexRoute: ChangePasswordIndexRoute,
  ForbiddenIndexRoute: ForbiddenIndexRoute,
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  AdminForgotPasswordSentRoute: AdminForgotPasswordSentRoute,
  AdminForgotPasswordIndexRoute: AdminForgotPasswordIndexRoute,
  AdminResetPasswordIndexRoute: AdminResetPasswordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
