/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./app/__root"
import { Route as LoginRouteImport } from "./app/login"
import { Route as ForbiddenRouteImport } from "./app/forbidden"
import { Route as CompanyRouteImport } from "./app/company"
import { Route as ChangePasswordRouteImport } from "./app/change-password"
import { Route as AdminRouteImport } from "./app/admin"
import { Route as AcceptInvitationRouteImport } from "./app/accept-invitation"
import { Route as IndexRouteImport } from "./app/index"
import { Route as AdminIndexRouteImport } from "./app/admin.index"
import { Route as CompanyDashboardRouteImport } from "./app/company.dashboard"
import { Route as AdminLoginRouteImport } from "./app/admin_.login"
import { Route as AdminSubscriptionsRouteImport } from "./app/admin.subscriptions"
import { Route as AdminPlansRouteImport } from "./app/admin.plans"
import { Route as AdminLeadsRouteImport } from "./app/admin.leads"
import { Route as AdminDashboardRouteImport } from "./app/admin.dashboard"
import { Route as AdminCompaniesRouteImport } from "./app/admin.companies"
import { Route as AdminAuditRouteImport } from "./app/admin.audit"
import { Route as AdminLeadsIndexRouteImport } from "./app/admin.leads.index"
import { Route as AdminCompaniesIndexRouteImport } from "./app/admin.companies.index"
import { Route as AdminLeadsPublicIdRouteImport } from "./app/admin.leads.$publicId"
import { Route as AdminCompaniesPublicIdRouteImport } from "./app/admin.companies.$publicId"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: "/forbidden",
  path: "/forbidden",
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: "/company",
  path: "/company",
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: "/change-password",
  path: "/change-password",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: "/accept-invitation",
  path: "/accept-invitation",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any)
const CompanyDashboardRoute = CompanyDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => CompanyRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: "/admin_/login",
  path: "/admin/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: "/subscriptions",
  path: "/subscriptions",
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: "/plans",
  path: "/plans",
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: "/leads",
  path: "/leads",
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompaniesRoute = AdminCompaniesRouteImport.update({
  id: "/companies",
  path: "/companies",
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: "/audit",
  path: "/audit",
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminCompaniesIndexRoute = AdminCompaniesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminCompaniesRoute,
} as any)
const AdminLeadsPublicIdRoute = AdminLeadsPublicIdRouteImport.update({
  id: "/$publicId",
  path: "/$publicId",
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminCompaniesPublicIdRoute = AdminCompaniesPublicIdRouteImport.update({
  id: "/$publicId",
  path: "/$publicId",
  getParentRoute: () => AdminCompaniesRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/accept-invitation": typeof AcceptInvitationRoute
  "/admin": typeof AdminRouteWithChildren
  "/change-password": typeof ChangePasswordRoute
  "/company": typeof CompanyRouteWithChildren
  "/forbidden": typeof ForbiddenRoute
  "/login": typeof LoginRoute
  "/admin/audit": typeof AdminAuditRoute
  "/admin/companies": typeof AdminCompaniesRouteWithChildren
  "/admin/dashboard": typeof AdminDashboardRoute
  "/admin/leads": typeof AdminLeadsRouteWithChildren
  "/admin/plans": typeof AdminPlansRoute
  "/admin/subscriptions": typeof AdminSubscriptionsRoute
  "/admin/login": typeof AdminLoginRoute
  "/company/dashboard": typeof CompanyDashboardRoute
  "/admin/": typeof AdminIndexRoute
  "/admin/companies/$publicId": typeof AdminCompaniesPublicIdRoute
  "/admin/leads/$publicId": typeof AdminLeadsPublicIdRoute
  "/admin/companies/": typeof AdminCompaniesIndexRoute
  "/admin/leads/": typeof AdminLeadsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/accept-invitation": typeof AcceptInvitationRoute
  "/change-password": typeof ChangePasswordRoute
  "/company": typeof CompanyRouteWithChildren
  "/forbidden": typeof ForbiddenRoute
  "/login": typeof LoginRoute
  "/admin/audit": typeof AdminAuditRoute
  "/admin/dashboard": typeof AdminDashboardRoute
  "/admin/plans": typeof AdminPlansRoute
  "/admin/subscriptions": typeof AdminSubscriptionsRoute
  "/admin/login": typeof AdminLoginRoute
  "/company/dashboard": typeof CompanyDashboardRoute
  "/admin": typeof AdminIndexRoute
  "/admin/companies/$publicId": typeof AdminCompaniesPublicIdRoute
  "/admin/leads/$publicId": typeof AdminLeadsPublicIdRoute
  "/admin/companies": typeof AdminCompaniesIndexRoute
  "/admin/leads": typeof AdminLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/accept-invitation": typeof AcceptInvitationRoute
  "/admin": typeof AdminRouteWithChildren
  "/change-password": typeof ChangePasswordRoute
  "/company": typeof CompanyRouteWithChildren
  "/forbidden": typeof ForbiddenRoute
  "/login": typeof LoginRoute
  "/admin/audit": typeof AdminAuditRoute
  "/admin/companies": typeof AdminCompaniesRouteWithChildren
  "/admin/dashboard": typeof AdminDashboardRoute
  "/admin/leads": typeof AdminLeadsRouteWithChildren
  "/admin/plans": typeof AdminPlansRoute
  "/admin/subscriptions": typeof AdminSubscriptionsRoute
  "/admin_/login": typeof AdminLoginRoute
  "/company/dashboard": typeof CompanyDashboardRoute
  "/admin/": typeof AdminIndexRoute
  "/admin/companies/$publicId": typeof AdminCompaniesPublicIdRoute
  "/admin/leads/$publicId": typeof AdminLeadsPublicIdRoute
  "/admin/companies/": typeof AdminCompaniesIndexRoute
  "/admin/leads/": typeof AdminLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/accept-invitation"
    | "/admin"
    | "/change-password"
    | "/company"
    | "/forbidden"
    | "/login"
    | "/admin/audit"
    | "/admin/companies"
    | "/admin/dashboard"
    | "/admin/leads"
    | "/admin/plans"
    | "/admin/subscriptions"
    | "/admin/login"
    | "/company/dashboard"
    | "/admin/"
    | "/admin/companies/$publicId"
    | "/admin/leads/$publicId"
    | "/admin/companies/"
    | "/admin/leads/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/accept-invitation"
    | "/change-password"
    | "/company"
    | "/forbidden"
    | "/login"
    | "/admin/audit"
    | "/admin/dashboard"
    | "/admin/plans"
    | "/admin/subscriptions"
    | "/admin/login"
    | "/company/dashboard"
    | "/admin"
    | "/admin/companies/$publicId"
    | "/admin/leads/$publicId"
    | "/admin/companies"
    | "/admin/leads"
  id:
    | "__root__"
    | "/"
    | "/accept-invitation"
    | "/admin"
    | "/change-password"
    | "/company"
    | "/forbidden"
    | "/login"
    | "/admin/audit"
    | "/admin/companies"
    | "/admin/dashboard"
    | "/admin/leads"
    | "/admin/plans"
    | "/admin/subscriptions"
    | "/admin_/login"
    | "/company/dashboard"
    | "/admin/"
    | "/admin/companies/$publicId"
    | "/admin/leads/$publicId"
    | "/admin/companies/"
    | "/admin/leads/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  CompanyRoute: typeof CompanyRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  LoginRoute: typeof LoginRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/forbidden": {
      id: "/forbidden"
      path: "/forbidden"
      fullPath: "/forbidden"
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/company": {
      id: "/company"
      path: "/company"
      fullPath: "/company"
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/change-password": {
      id: "/change-password"
      path: "/change-password"
      fullPath: "/change-password"
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin": {
      id: "/admin"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/accept-invitation": {
      id: "/accept-invitation"
      path: "/accept-invitation"
      fullPath: "/accept-invitation"
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    "/company/dashboard": {
      id: "/company/dashboard"
      path: "/dashboard"
      fullPath: "/company/dashboard"
      preLoaderRoute: typeof CompanyDashboardRouteImport
      parentRoute: typeof CompanyRoute
    }
    "/admin_/login": {
      id: "/admin_/login"
      path: "/admin/login"
      fullPath: "/admin/login"
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/subscriptions": {
      id: "/admin/subscriptions"
      path: "/subscriptions"
      fullPath: "/admin/subscriptions"
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/plans": {
      id: "/admin/plans"
      path: "/plans"
      fullPath: "/admin/plans"
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/leads": {
      id: "/admin/leads"
      path: "/leads"
      fullPath: "/admin/leads"
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/dashboard": {
      id: "/admin/dashboard"
      path: "/dashboard"
      fullPath: "/admin/dashboard"
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/companies": {
      id: "/admin/companies"
      path: "/companies"
      fullPath: "/admin/companies"
      preLoaderRoute: typeof AdminCompaniesRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/audit": {
      id: "/admin/audit"
      path: "/audit"
      fullPath: "/admin/audit"
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    "/admin/leads/": {
      id: "/admin/leads/"
      path: "/"
      fullPath: "/admin/leads/"
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    "/admin/companies/": {
      id: "/admin/companies/"
      path: "/"
      fullPath: "/admin/companies/"
      preLoaderRoute: typeof AdminCompaniesIndexRouteImport
      parentRoute: typeof AdminCompaniesRoute
    }
    "/admin/leads/$publicId": {
      id: "/admin/leads/$publicId"
      path: "/$publicId"
      fullPath: "/admin/leads/$publicId"
      preLoaderRoute: typeof AdminLeadsPublicIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    "/admin/companies/$publicId": {
      id: "/admin/companies/$publicId"
      path: "/$publicId"
      fullPath: "/admin/companies/$publicId"
      preLoaderRoute: typeof AdminCompaniesPublicIdRouteImport
      parentRoute: typeof AdminCompaniesRoute
    }
  }
}

interface AdminCompaniesRouteChildren {
  AdminCompaniesPublicIdRoute: typeof AdminCompaniesPublicIdRoute
  AdminCompaniesIndexRoute: typeof AdminCompaniesIndexRoute
}

const AdminCompaniesRouteChildren: AdminCompaniesRouteChildren = {
  AdminCompaniesPublicIdRoute: AdminCompaniesPublicIdRoute,
  AdminCompaniesIndexRoute: AdminCompaniesIndexRoute,
}

const AdminCompaniesRouteWithChildren = AdminCompaniesRoute._addFileChildren(
  AdminCompaniesRouteChildren,
)

interface AdminLeadsRouteChildren {
  AdminLeadsPublicIdRoute: typeof AdminLeadsPublicIdRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsPublicIdRoute: AdminLeadsPublicIdRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCompaniesRoute: typeof AdminCompaniesRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminCompaniesRoute: AdminCompaniesRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminPlansRoute: AdminPlansRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CompanyRouteChildren {
  CompanyDashboardRoute: typeof CompanyDashboardRoute
}

const CompanyRouteChildren: CompanyRouteChildren = {
  CompanyDashboardRoute: CompanyDashboardRoute,
}

const CompanyRouteWithChildren =
  CompanyRoute._addFileChildren(CompanyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  CompanyRoute: CompanyRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  LoginRoute: LoginRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
